/* eslint-disable @next/next/no-img-element */
import Link from 'next/link'
import Image from 'next/image'
import styles from './page.module.scss';


export const metadata = {
  title: 'Kancelaria Zembowicz',
  description: 'Generated by create next app',
}


export default function Home() {
  return (
    <>

    <div className={styles.container}>
      <div className={styles.hero}>
        <img className={styles.image} src="/main_1.png" alt="Logo" />
        <div className={styles.hero_text}>
          <h1>RADCA <br /> PRAWNY <br /> RENATA <br /> ZEMBOWICZ</h1>
          <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ullam ab exercitationem debitis culpa natus, ratione ipsum sed iure odio nemo impedit, omnis quae voluptates in facilis dolore minus consectetur est. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ullam ab exercitationem debitis culpa natus, ratione ipsum sed iure odio nemo impedit, omnis quae voluptates in facilis dolore minus consectetur est. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ullam ab exercitationem debitis culpa natus, ratione ipsum sed iure odio nemo impedit, omnis quae voluptates in facilis dolore minus consectetur est.</p>
        </div>
      </div> 

      <div className={styles.info}>
        <div className={styles.info_left}>
          <h2>CZYM SIE ZAJMUJEMY</h2>
          <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Facere vero tempora minus odit, ab voluptatem maxime nulla eum, doloremque assumenda quaerat! Et accusamus ut corporis! Itaque unde ea rem nobis! Lorem ipsum dolor sit amet, consectetur adipisicing elit. Facere vero tempora minus odit, ab voluptatem maxime nulla eum, doloremque assumenda quaerat! Et accusamus ut corporis! Itaque unde ea rem nobis! Lorem ipsum dolor sit amet, consectetur adipisicing elit. Facere vero tempora minus odit, ab voluptatem maxime nulla eum, doloremque assumenda quaerat! Et accusamus ut corporis! Itaque unde ea rem nobis!</p>
          <ul>
            <li>Lorem ipsum</li>
            <li>Lorem ipsum</li>
            <li>Lorem ipsum</li>
            <li>Lorem ipsum</li>
            <li>Lorem ipsum</li>
            <li>Lorem ipsum</li>
          </ul>
        </div>
        <div className={styles.info_right}>
          <img src="/page_1_2.png" alt="law lady" />
        </div>
      </div>

      <div className={styles.line}></div>

      <div className={styles.partners}>
        <h2>NASI PARTNERZY</h2>
        <div className={styles.names}>
          <img src="/partners.png" alt="" />
          <img src="/partners.png" alt="" />
          <img src="/partners.png" alt="" />
          <img src="/partners.png" alt="" />
          <img src="/partners.png" alt="" />
          <img src="/partners.png" alt="" />
        </div>
      </div>

      <div className={styles.line}></div>

      <div className={styles.why}>
        <h2>DLACZEGO ZEMBOWICZ KANCELARIA?</h2>
        <ul>
          <li>
            <img src="/Component_1.svg" alt="" />
            <p>
              Lorem ipsum dolor, sit amet consectetur adipisicing elit. Perspiciatis autem aspernatur doloremque doloribus ducimus eligendi eaque libero expedita iusto rem accusantium voluptatum corporis soluta, veritatis est numquam labore quos blanditiis?
            </p>
          </li>
          <li>
          <img src="/Component_2.svg" alt="" />
            <p>
              Lorem ipsum dolor, sit amet consectetur adipisicing elit. Perspiciatis autem aspernatur doloremque doloribus ducimus eligendi eaque libero expedita iusto rem accusantium voluptatum corporis soluta, veritatis est numquam labore quos blanditiis?
            </p>
          </li>
          <li>
          <img src="/Component_3.svg" alt="" />
            <p>
              Lorem ipsum dolor, sit amet consectetur adipisicing elit. Perspiciatis autem aspernatur doloremque doloribus ducimus eligendi eaque libero expedita iusto rem accusantium voluptatum corporis soluta, veritatis est numquam labore quos blanditiis?
            </p>
          </li>
          <li>
          <img src="/Component_4.svg" alt="" />
            <p>
              Lorem ipsum dolor, sit amet consectetur adipisicing elit. Perspiciatis autem aspernatur doloremque doloribus ducimus eligendi eaque libero expedita iusto rem accusantium voluptatum corporis soluta, veritatis est numquam labore quos blanditiis?
            </p>
          </li>
          <li>
          <img src="/Component_5.svg" alt="" />
            <p>
              Lorem ipsum dolor, sit amet consectetur adipisicing elit. Perspiciatis autem aspernatur doloremque doloribus ducimus eligendi eaque libero expedita iusto rem accusantium voluptatum corporis soluta, veritatis est numquam labore quos blanditiis?
            </p>
          </li>
          <li>
          <img src="/Component_6.svg" alt="" />
            <p>
              Lorem ipsum dolor, sit amet consectetur adipisicing elit. Perspiciatis autem aspernatur doloremque doloribus ducimus eligendi eaque libero expedita iusto rem accusantium voluptatum corporis soluta, veritatis est numquam labore quos blanditiis?
            </p>
          </li>
        </ul>
      </div>

      <div className={styles.line}></div>

      <div className={styles.info}>
        <div className={styles.info_right}>
          <img src="/page_1_3.png" alt="Warsaw" />
        </div>
        <div className={styles.info_left}>
          <h2>Adwocati i prawnicy w kancelaria ZEMBOWICZ</h2>
          <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Facere vero tempora minus odit, ab voluptatem maxime nulla eum, doloremque assumenda quaerat! Et accusamus ut corporis! Itaque unde ea rem nobis! Lorem ipsum dolor sit amet, consectetur adipisicing elit. Facere vero tempora minus odit, ab voluptatem maxime nulla eum, doloremque assumenda quaerat! Et accusamus ut corporis! Itaque unde ea rem nobis! Lorem ipsum dolor sit amet, consectetur adipisicing elit. Facere vero tempora minus odit, ab voluptatem maxime nulla eum, doloremque assumenda quaerat! Et accusamus ut corporis! Itaque unde ea rem nobis!</p>
          <ul>
            <li>Lorem ipsum</li>
            <li>Lorem ipsum</li>
            <li>Lorem ipsum</li>
            <li>Lorem ipsum</li>
            <li>Lorem ipsum</li>
            <li>Lorem ipsum</li>
            <li>Lorem ipsum</li>
            <li>Lorem ipsum</li>
          </ul>
        </div>
      </div>

    </div>
      
    </>
  )
}
